### PR TITLE
Show general status text bar and block syncing progress

### PR DESCRIPTION
**Pull request by lvaccaro**
The idea is to show a progressbar until the chain is not synced under the title bar. Design/Funcional feedbacks are welcome.

On `getinfo`, it checks the `warning_lightningd_sync` field: if it exists, it shows a progressbar and it schedules a new `getinfo` command after 10s. That timer is cancelled on next `getInfo` or at activity `onPause()`.

Close https://github.com/lvaccaro/lamp/issues/18

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
ack 55e1972d6439c67c45cfea5735a93b4ef398c5fe

**Comment by darosior** [comment]
Tested ACK % Travis lints

**Comment by darosior** [comment]
If I may, i think this would be better from an UX perspective to display the progress on the bar or ideally the number of blocks left to go.

**Comment by lvaccaro** [comment]
I agree, in that case it should be even better to add a fixed status line for: printing missing blocks during syncing, advise during booting daemon phase, if you need to download the binary, rubbing the lamp to start.

**Comment by darosior** [comment]
Agreed! Also for gossip sync even if you can't really tell if it's finished yet ;)
-------- Original Message --------

**Comment by lvaccaro** [comment]
Rewrite code with a general purpose status textview on main activity to show current node status:
- offline, without binaries
- offline, downloading binaries & uncompressing
- offline, ready to start
- starting tor, lightning
- syncing blocks
- online

Note: when a node is not synced yet, a timer watches every 5sec blockcount information and update missing blocks.

**Comment by darosior** [comment]
The status organisation LGTM, will scheme through the code and test tomorrow.

**Comment by lvaccaro** [comment]
Think to merge, more UI improvements will be included in a next design MR.

**Pull request merged**
