### PR TITLE
Share content log like plain text wiht other android apps

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
This PR depends on https://github.com/lvaccaro/lamp/pull/52 and adds the possibility to share the log with the developers. (I added my email and but I want to add also a @lvaccaro email :-) )

The problem here is that the log is too large to share it by email and I added the code to share only the 200 lines.

At the moment this is only the draft code to add this function and try to work with it, but in the future, I think using some android structure is the better choice to work with Log data.

This commit requires refactoring in the future

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Rebased.

@lvaccaro do you think is good to add a generic email such as "lamp.info@protonmail.com" or gmail?

**Comment by lvaccaro** [comment]
I prefer not define any receiver's email. The user could also send the log file to himself.

**Comment by vincenzopalazzo** [comment]
@lvaccaro do you mean that the user should be able to specify the email or you don't want a method to share the log information directly to the app?

**Comment by lvaccaro** [comment]
That's great send log via email, I really like it; on the other hand, I prefer not specify any email address for support right now.

**Comment by vincenzopalazzo** [comment]
Oh yes, absolutely. I will remove the email inside the code today.

**Comment by vincenzopalazzo** [comment]
Rebase and moved it the intent from `SENDTO` to `SEND`, now is possible to share the message with all type of chat application.

Thanks to upgrading my code @lvaccaro :-)

**Comment by lvaccaro** [comment]
ack 891387487a0340e5f104a21db8c12ccb67f7bbb1

**Pull request merged**
