### PR TITLE
doc: Update cmdline-tools-setup.md

### PR DESCRIPTION
**Pull request by jsarenik**

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Thanks to continuing improving this document :-) I like it @jsarenik

**Comment by jsarenik** [comment]
@vincenzopalazzo you are welcome! That's why it's good to do something else for a while and then get back and start from scratch :-) Thank you!

**Comment by vincenzopalazzo** [comment]
@jsarenik you have right, I'm learning day by day that you can have the idea more clear when you stop to break your mind on some problem and you will start to do other stuff. I tested that this technique and it works very well if you are doing bug fixing :-).

Good talk with you :-)

**Comment by lvaccaro** [comment]
ack 078f40d024f48fc0c5ded36393eafa12abd358de

it looks like a good starting point for a docker environment.

**Pull request merged**
