### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by lvaccaro**
- ui: update header labels text color to white for main, receive and send activities
- bitcoin: add receive bitcoin functionality on receive activity
- fix: update alert error message
- fix: run handler notifications on UI Thread

Note: this PR include https://github.com/lvaccaro/lamp/pull/83 commits

### CODE REVIEW

**Comment by darosior** [comment]
Hmm so the v0.9.2 is taking forever at the "uncompressing" stage for me

**Comment by vincenzopalazzo** [comment]
@darosior maybe this @lvaccaro explanation can help https://github.com/lvaccaro/lamp/issues/80#issuecomment-733235047

We updated the logic behind

**Comment by darosior** [comment]
Thanks, that was it. Shouldn't have tried to cut-through the issues check :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vincenzopalazzo** [comment]
@darosior don't worry, we need to update the readme :)

**Review by darosior — APPROVED** [review]
59be5f5 looks good to me. I tested the v0.9.2 update and the UI is nice but did not review.

The UX definitely gets better each month :-)

**Pull request merged**
