### PR TITLE
Main Activity design updates

### PR DESCRIPTION
**Pull request by lvaccaro**
Design proposal to improve main page UI:
- yellow color instead green on actionbar
- removing app night theme and dark background on offline mode
- menu show/hide elements based on online/offline lightning status
- add stop button on menu
- increase qr code dimension

Screenshot_1594802286
Screenshot_1594802289
Screenshot_1594802292
Screenshot_1594802296
Screenshot_1594802302

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Hi @lvaccaro,

Looks very good, and with the label is cleaner what is happening :) thanks @darosior for this suggestion.

I want to add only my personal opinion, you are free to ignore it :)

1. I like a lot the node QR with the previous layout like the photo below

Selection_044

2. The yellow color is a little more clear and maybe with some display this yellow is more "white"? Maybe we can use yellow darker? (only personal opinion)

3. If you agree with my n.1 we can use the space in the middle of the screen to display the about onchain and offchain amount? we can write some code that looks like the plugin `funds` of Rene Pickhardt.

I made a java plugin that returns somethings like this a few days ago

```json
{
   "onchain_value": 1.483222631E9,
   "offchain_value": 1.6777215E7
}
```

I will not be in front my desk in the next 2 day and If I don't answer at your "answer" I'm not ignoring you but I'm only not in front of my desk :)

**Comment by lvaccaro** [comment]
Thanks for comments, adding some notes:

1. QR code is used to connect the node, that it looks a rarely used features. But in the future, it could be used for Keysend feature; so the previous version was too little and this is too big.

2. Maybe a darker yellow as 0xfdd835 could be better https://material.io/resources/color/#!/?primary.color=FDD835

3. I am ok to add information as `listfunds`. This command could be run after `getchaininfo` and add to the status text or somewhere. Now `getchaininfo` is running only when daemon is ready. Do you think we should monitoring it in order to update the value? For example, scheduling a timer for listfunds or reading logs?

**Comment by vincenzopalazzo** [comment]
Hi @lvaccaro,

Thank, you to give me the opportunity to express my opinion.

>QR code is used to connect the node, that it looks rarely used features. But in the future, it could be used for Keysend feature; so the previous version was too little and this is too big.

I'm excited about the Keysend function, about your consideration,

>so the previous version was too little and this is too big.

Maybe, we can restore the previous layout, and adding an onClickListener to the big QR in a dialog?

>Maybe a darker yellow as 0xfdd835 could be better https://material.io/resources/color/#!/?primary.color=FDD835

We can test also this and see the difference. :smile: 

>I am ok to add information as listfunds. This command could be run after getchaininfo and add to the status text or somewhere. Now getchaininfo is running only when daemon is ready and when main activity is resumed. Do you think we should monitoring it in order to update the value? For example, scheduling a timer for listfunds or reading logs?

I think also I to read the logs, but I want to share the idea to update the UI to runtime with the hooks, I'm developing an RPC java wrapper that you can found [here](https://github.com/vincenzopalazzo/JRPClightning) and in this version, I'm using a library not for android to use the Unix socket. But the app can support different RPC library, maybe we can search for something like unix rpc on android and use this library to write a plugin to help us to work with lightningd? (we implement also plugin like autopilot in java and support this in lamp project)

Also, without the possibility to listen to hooks I like this is a good idea :smile: 

>Pensi che dovremmo monitorarlo per aggiornare il valore? Ad esempio, programmare un timer per i listfund o leggere i registri?

**Comment by lvaccaro** [comment]
- Maybe big QR code could be misleading because some pages use big QR code for btc address and bolt11. So reverting to the small one.

- This is the main page with Amber color 0xFFC107
Screenshot_1595079355

- I am pretty sure we could build some solutions to listen under the hood, but I prefer for now to keep as simple as possible and build one at time.

**Comment by darosior** [comment]
Nice. I'm usually not a fan of white backgrounds (more kinda dark theme person) but it's nice and `0xFFC107` is pretty.

Your PR's target branch is already merged though.

Now testing on my wallet.

**Comment by darosior** [comment]
Tested ACK 933d153. Love it !

The stop button seems redundant with the lamp though (not important).

**Comment by lvaccaro** [comment]
Thanks, agree with the nit.. I'll keep in mind for next improvements :-)

**Pull request closed without merging**
