### PR TITLE
Add globber for android api < VERSION_CODE.O

### LINKED ISSUE #2: Integrated tor won't start
I encounter an error at launch : `Tor start failed`.
Trying to check the logs I get `No log file found`.

I run Android 7.1.1 on a BV9000.

Trying with Orbot and activating local proxy I got `Lightning start failed`, but I still cant check the logs.

### PR DESCRIPTION
**Pull request by lvaccaro**
Create a local file logger `Globber` for redirect process output/error is android api < VERSION_CODE.O . For more recent Android version, it could be used ProcessBuilder.redirectOutput() .

Close #2

### CODE REVIEW

**Comment by darosior** [comment]
Thanks ! Testing this now.

**Comment by lvaccaro** [comment]
Sorry, to have merged too soon.. let me know..

**Comment by darosior** [comment]
Sure, I would never had have the notification otherwise :)

**Comment by darosior** [comment]
It just worked. Thanks !

**Pull request merged**
