### PR TITLE
Update lightning_ndk to release_clightning_0.9.1

### PR DESCRIPTION
**Pull request by lvaccaro**
Update lightning_ ndk to https://github.com/lvaccaro/lightning_ndk/releases/tag/release_clightning_0.9.1

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
I'm not sure, but at the moment I'm not able to run this version with lightnind 0.9.1 on my Pixel XL 4, and also no log is a provider. I will look more in deep in the few days to provide more information about it

**Review by darosior — APPROVED** [review]
ACK 2aa11f3 :tada:

**Comment by vincenzopalazzo** [comment]
Hi  @darosior, how you run the application?

because I have still a problem with this PR, I make a little bit of test and I found this message

```
I/Gralloc4: mapper 4.x is not supported
I/UriResultActivity: Permission has been granted by user
W/m.lvaccaro.lam: Accessing hidden field Landroid/widget/AbsListView;->mIsChildViewEnabled:Z (greylist, reflection, allowed)
D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10486; state: DISABLED
D/OpenGLRenderer: endAllActiveAnimators on 0x6fe1abc570 (MenuPopupWindow$MenuDropDownListView) with handle 0x6f01ac5920
D/UriResultActivity: /data/user/0/com.lvaccaro.lamp/no_backup/lightningd.log: open failed: ENOENT (No such file or directory)
I/LightningService: start lightningd service
I/LightningService: exit lightningd service
D/com.lvaccaro.lamp.utils.LogObserver: /data/user/0/com.lvaccaro.lamp/no_backup/lightningd
D/com.lvaccaro.lamp.utils.LogObserver: ": library "libsqlite3.so" not found: needed by main executable
```

I know that @lvaccaro worked on an issue related of sqllite, maybe this can help

Again, what is your device @darosior? or maybe you are not cleaning the directory before to run lightnind v0.9.1?

**Comment by darosior** [comment]
You are missing a shared library. Have you the `sqlite3` (or similar) package installed ?

**Comment by lvaccaro** [comment]
I think it try to link sqlite3 as shared object instead static library, https://github.com/lvaccaro/lightning_ndk/commit/a8f07f9c5b5a60ee564f8e1d0dce22ec98830009 should fix.

Unfortunately "--plugin-dir" looks not working anymore on v0.9.1 .

**Comment by vincenzopalazzo** [comment]
@lvaccaro I will test today the new ndk, thank to work on this.

> Unfortunately "--plugin-dir" looks not working anymore on v0.9.1 .

Maybe the deprecated time ended https://github.com/ElementsProject/lightning/commit/34a62940315b5e0e1720dab34adb720bf113c004

>You are missing a shared library. Have you the sqlite3 (or similar) package installed ?

@darosior, Mh maybe the lib is inside the android system, I don't touch nothings :-)

**Comment by darosior** [comment]
> It tries to link sqlite3 as shared object instead static library, lvaccaro/lightning_ndk@a8f07f9 should fix. I am re-deploying cross-compiled binaries.

Interestingly, the shared object library worked for me.

> Unfortunately "--plugin-dir" looks not working anymore on v0.9.1 .

Do you give it an absolute path ?

**Comment by lvaccaro** [comment]
"--plugin-dir" I am using the absolute path, same story also on my vanilla lightningd version on laptop.

In lightning, configure tries to detect the sqlite3 and set same global vars in config.vars file . Sqlite3 was not detected when I compiled by myself and https://github.com/lvaccaro/lightning_ndk/commit/a8f07f9 sets the missing vars.

**Comment by vincenzopalazzo** [comment]
During the uncompress faces I receive the following exception, maybe for you is more easily understand what is happening under the hood.

```
W/Gralloc3: mapper 3.x is not supported
W/System.err: java.io.FileNotFoundException: /data/user/0/com.lvaccaro.lamp/no_backup/lightningd/lightning_channeld: open failed: ENOTDIR (Not a directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at com.lvaccaro.lamp.utils.Archive.uncompressXZ(Archive.kt:35)
        at com.lvaccaro.lamp.MainActivity$onPowerClick$2.invoke(MainActivity.kt:391)
        at com.lvaccaro.lamp.MainActivity$onPowerClick$2.invoke(MainActivity.kt:57)
        at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:140)
        at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
        at org.jetbrains.anko.AsyncKt$sam$Callable$761a5578.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    Caused by: android.system.ErrnoException: open failed: ENOTDIR (Not a directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
        at libcore.io.IoBridge.open(IoBridge.java:478)
    	... 13 more
```

**Comment by lvaccaro** [comment]
Hi, pretty sure it should be fixed in fa456e2

**Comment by vincenzopalazzo** [comment]
@lvaccaro you have complete right, I miss erasing the old directory. Sorry about that

Now I'm able to see the "delpay" command :-)

HACK https://github.com/lvaccaro/lamp/commit/fa456e2c059b91382620f1756c3c6e54d085dcb8

**Pull request merged**
